"""Exercise the actual Streamlit upload/Analyse/results/download workflow.

Official data stay outside the repository. No predictions are preloaded into
session state. All result files are generated by clicking Analyse in AppTest.
"""
from __future__ import annotations
import argparse
import json
import resource
from pathlib import Path
import pandas as pd
from streamlit.testing.v1 import AppTest
from src.app.maintenance import summary_html
from src.app.submission import predictions_zip
from src.app.validators import validate_zip


def main():
    parser=argparse.ArgumentParser()
    parser.add_argument("--data",type=Path,required=True,help="Official 02_Datasets directory")
    parser.add_argument("--acv-test",type=Path,required=True)
    parser.add_argument("--output",type=Path,required=True)
    parser.add_argument("--full",action="store_true",help="Use all 68 Rail and all 16 SHM test files")
    args=parser.parse_args()
    root=Path(__file__).resolve().parents[1]
    at=AppTest.from_file(str(root/"app.py"),default_timeout=300).run()
    assert not at.exception,[e.message for e in at.exception]
    report={"workflow":"Actual Streamlit AppTest upload and Analyse button", "subsystems":{}}
    selected={
        "door":[args.data/"Door/Test.csv"],
        "acv":[args.acv_test],
        "rail":sorted((args.data/"Rail_Corrugation/Test").glob("*.csv"),key=lambda p:int(p.stem[4:])),
        "shm":sorted((args.data/"SHM/Test").glob("*.csv")),
    }
    if not args.full:
        selected["rail"]=selected["rail"][:2]
        selected["shm"]=selected["shm"][:2]
    if args.full:
        assert len(selected["rail"])==68
        assert len(selected["shm"])==16
    for key,paths in selected.items():
        uploads=[("acv_test_case.xlsx" if key=="acv" else p.name,p.read_bytes(),
                  "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" if key=="acv" else "text/csv") for p in paths]
        at.file_uploader(key=f"uploads_{key}").set_value(uploads[0] if key=="door" else uploads).run()
        assert not at.button(key=f"analyse_{key}").disabled
        at.button(key=f"analyse_{key}").click().run()
        assert not at.exception,[e.message for e in at.exception]
        assert not at.error,[e.value for e in at.error]
        result=at.session_state["results"][key]
        assert not result.validation_errors()
        args.output.mkdir(parents=True,exist_ok=True)
        (args.output/result.filename).write_bytes(result.csv_bytes)
        report["subsystems"][key]={"files":len(paths),"prediction_rows":len(result.table),
                                  "seconds":result.elapsed_seconds,"validation":"passed"}
        if key=="door":
            detail=result.diagnostics["by_file"]["Test.csv"]
            cycles=pd.DataFrame(detail["cycles"])
            report["subsystems"][key].update(input_rows=detail["input_rows"],
                labels=cycles.prediction.value_counts().to_dict(),
                operations=cycles.operation.value_counts().to_dict(),
                ambiguous=detail["ambiguous_operations"])
        if key=="acv":
            report["subsystems"][key]["ranking"]=result.table.iloc[0].ranked_cars
        if key=="rail":
            report["subsystems"][key]["labels"]=result.table.prediction.value_counts().to_dict()
            report["subsystems"][key]["low_speed_rule_count"]=sum(len(d["low_speed_rule"]) for d in result.diagnostics["by_file"].values())
        print(key,report["subsystems"][key],flush=True)
        del uploads
    assert not at.exception,[e.message for e in at.exception]
    archive=predictions_zip(at.session_state["results"])
    assert not validate_zip(archive)
    (args.output/"predictions.zip").write_bytes(archive)
    html=summary_html(at.session_state["results"])
    (args.output/"maintenance_summary.html").write_bytes(html)
    assert b"4 of 4 subsystems checked" in html
    assert len(at.tabs)==4 and not at.sidebar.radio
    assert any(d.label=="Download summary report" for d in at.get("download_button"))
    # Subsystem navigation must preserve the other generated outputs.
    assert set(at.session_state["results"])==set(selected)
    # A malformed replacement must remove the old result and show a friendly error.
    at.file_uploader(key="uploads_door").set_value(("bad.csv",b"wrong,data\n1,2\n","text/csv")).run()
    at.button(key="analyse_door").click().run()
    assert not at.exception
    assert at.error and "door" not in at.session_state["results"]
    assert set(at.session_state["results"])=={"acv","rail","shm"}
    # Clearing the uploader removes its output and cannot leave a stale report.
    at.file_uploader(key="uploads_acv").set_value([]).run()
    assert not at.exception
    assert set(at.session_state["results"])=={"rail","shm"}
    assert b"2 of 4 subsystems checked" in summary_html(at.session_state["results"])
    report["report_and_clear_upload"]="passed"
    report["malformed_upload"]="friendly error; stale output removed"
    report["zip_validation"]="passed"
    report["process_peak_rss_mib"]=resource.getrusage(resource.RUSAGE_SELF).ru_maxrss/1024
    (args.output/"verification.json").write_text(json.dumps(report,indent=2)+"\n")
    print(json.dumps(report,indent=2),flush=True)


if __name__=="__main__":
    main()
